---
- hosts: all
  tasks:

#pered ustanovkoi paketov i ostalnogo, obnovlajem paketi
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

# ustanovka poslednei versii nginx, takze zapuskaetsa sam serviss    
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started

# primer perezagruzki servisa, vdanom slucaje perezapskaem serviss vremeni
#    - name: restart time (perezagruzka)
#      shell:
#        cmd: sudo systemctl restart systemd-timesyncd.service
# eto plohoi stilj, poetomu budu shell polzovatsa, tolko v isklucitelnih slucahah

# ustanovka php-fpm
    - name: ustanovka php fpm
      apt: name=php-fpm

# ustanovka php-mysql
    - name: ustanovka sql
      apt: name=php-mysql

# sozdaem direktoriju /var/www/your_domain
    - name: Create a directory if it does not exist
      file:
        path: /var/www/your_domain
        state: directory
        mode: '0755'

# kopiruem nginx konfiguracionnij fail
    - name: If follow=yes, /path/to/file will be overwritten 
      copy:
        src: /home/ubuntu/conf_files/your_domain
        dest: /etc/nginx/sites-available/
        follow: yes

  # sozdaem link 
    - name: Create a symbolic link
      file:
        src: /etc/nginx/sites-available/your_domain
        dest: /etc/nginx/sites-enabled
        state: link

  #   - name: kopiruem index fail
    - name: If follow=yes, /path/to/file will be overwritten 
      copy:
        src: /home/ubuntu/conf_files/index.htm
        dest: /var/www/your_domain
        follow: yes
 

 
 
 #   - name: restart time (perezagruzka nginx)
 #     shell:
 #       cmd: sudo systemctl reload nginx


    - name: ustanovka mysql
      apt: name=mysql-server
    - name: ustanovka modlja dlja importa sql dump
      apt: name=python3-pymysql

#iz faila bekapa test.sql impotiruem bazu dannih s gotovoi strukturoi postfix bazi dannih
    - name: Restore database
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: mailserver
        state: import
        target: /home/ubuntu/conf_files/test.sql


